acertijos = [
    {'descripcion': 'Tiene llaves sin cerraduras, montañas sin tierras y te sigue constantemente.', 'respuesta': 'nube', 'imagen_url': ''},
    {'descripcion': 'Cuanto más lo quites, más grande se vuelve.', 'respuesta': 'hoyo', 'imagen_url': ''},
    {"descripcion": "Tengo dientes pero no muerdo, hablo pero no tengo boca.", "respuesta": "un peine", "imagen_url": ""},
    {"descripcion": "Siempre sube y nunca baja.", "respuesta": "la edad", "imagen_url": ""},
    {"descripcion": "Siempre está por delante, pero nunca se ve.", "respuesta": "el futuro", "imagen_url": ""},
    {"descripcion": "Siempre avanza pero nunca se mueve.", "respuesta": "el tiempo", "imagen_url": ""},
    {"descripcion": "Mientras más me quites, más grande me hago.", "respuesta": "un agujero", "imagen_url": ""},
    {"descripcion": "Soy más poderoso que Dios, más malvado que el diablo. Los pobres lo tienen, los ricos lo necesitan, y si lo comes, morirás.", "respuesta": "nada", "imagen_url": ""},
    {"descripcion": "Puedo ser largo o corto, soy redondo o cuadrado.", "respuesta": "la sombra", "imagen_url": ""},
    {"descripcion": "Puedes escucharme pero nunca hablo.", "respuesta": "un oído", "imagen_url": ""},
    {"descripcion": "Soy oscuro como la noche pero brillante como el día.", "respuesta": "una lámpara", "imagen_url": ""},
    {"descripcion": "Siempre estoy por delante, pero nunca me ves.", "respuesta": "el futuro", "imagen_url": ""},
    {"descripcion": "Siempre estoy húmedo cuando me usan, y el sol me convierte en algo duro.", "respuesta": "una toalla", "imagen_url": ""},
    {"descripcion": "Puedes romperme sin tocarme ni verme.", "respuesta": "una promesa", "imagen_url": ""},
    {"descripcion": "Aunque me nombres, desaparezco. ¿Qué soy?", "respuesta": "el silencio", "imagen_url": ""},
    {"descripcion": "Tengo ojos pero no puedo ver.", "respuesta": "la papa", "imagen_url": ""},
    {"descripcion": "Nunca descansas mientras me usas, siempre me buscas pero nunca me encuentras.", "respuesta": "un ratón", "imagen_url": ""},
    {"descripcion": "Soy frío como el hielo pero no me derrito, puedo contener agua pero no soy un vaso.", "respuesta": "un refrigerador", "imagen_url": ""},
    {"descripcion": "Soy redondo como una rueda pero nunca me muevo.", "respuesta": "un reloj", "imagen_url": ""},
    {"descripcion": "Soy pequeño como un ratón, pero guardo un mundo en mi interior.", "respuesta": "una memoria", "imagen_url": ""},
    {"descripcion": "Tengo una cabeza y una cola, pero no tengo cuerpo.", "respuesta": "una moneda", "imagen_url": ""},
    {"descripcion": "Soy suave como una pluma, pero incluso el más fuerte no puede sostenerme por mucho tiempo.", "respuesta": "el aliento", "imagen_url": ""},
]
